### ISSUE TITLE
Feature Request: support manual page breaks

### ISSUE THREAD

**Issue by sjsadowski** [HollowMan6/mdbook-pdf#22]
In some cases it makes sense to define where pages should break such as around images so that they are rendered on a single page.

This might be accomplished with
```html 
<!-- PAGE_BREAK -->
```

Then in the html a CSS rule could be inserted, something like
```css
@media print {
    .pagebreak { page-break-before: after; } 
}
```
and then replacing the PAGE_BREAK instruction with an empty div:
```html
<div class="pagebreak"></div>
```

I have been successfully using the plugin otherwise, and am happy to continue doing so - this would just be a quality-of-life improvement.
