### ISSUE TITLE
feature request: Generate PDF with page outlines

### ISSUE THREAD

**Issue by schwrzstrbn** [HollowMan6/mdbook-pdf#3]
> I'm not sure what you mean by "outlines"?

Maybe adding a new keyword in `output.html.print`, like `outline = true/false`

```toml
[output.html.print]
enable = true
page-break = true
outline = true # new keyword to include the 'ToC' in pdf print.
```

_Originally posted by @schwrzstrbn in https://github.com/rust-lang/mdBook/issues/1817#issuecomment-1163854290_
